name: CI Dev Deployment (CI 開發部署)
on:
  push:
    branches: [ master ]  # 使用 master 分支

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev (開發環境)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare deployment
        run: echo "Deploying to dev environment"

      - name: Create dev release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: dev-v${{ github.run_number }}  # 使用運行號碼生成唯一標籤
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          if [ -f build.zip ]; then
            gh release create "$TAG" build.zip --notes "$NOTE" --generate-notes
          else
            echo "No build.zip found, skipping release"
            exit 0
          fi

  build:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate build
        run: |
          echo "Generating build artifact"
          zip -r build.zip . -x "*.git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  deploy-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging (預備環境)
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Create staging release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: staging-v${{ github.run_number }}  # 使用運行號碼生成唯一標籤
          NOTE: "Testing pre-production release"
        run: |
          if [ -f build.zip ]; then
            gh release create "$TAG" build.zip --notes "$NOTE" --generate-notes
          else
            echo "No build.zip found, skipping release"
            exit 0
          fi

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production (生產環境)
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Create production release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: prod-v${{ github.run_number }}  # 使用運行號碼生成唯一標籤
          NOTE: "Production release"
        run: |
          if [ -f build.zip ]; then
            gh release create "$TAG" build.zip --notes "$NOTE" --generate-notes
          else
            echo "No build.zip found, skipping release"
            exit 0
          fi
