name: CI Dev Deployment (CI 開發部署)
on:
  push:
    branches: [ master ]  # 使用 master 分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code - 名稱：結帳代碼
        uses: actions/checkout@v4

      - name: Simulate build
        run: |
          echo "Generating build artifact"
          zip -r build.zip . -x "*.git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./release-artifacts

      - name: Create dev release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          cd ./release-artifacts
          if [ -f build.zip ]; then
            echo "Found build.zip, creating release with TAG=$TAG and NOTE=$NOTE"
            gh release create "$TAG" ./build.zip --notes "$NOTE" || { echo "Release creation failed: $?"; exit 0; }
          else
            echo "No build.zip found, skipping release"
            ls -la
            exit 0
          fi

  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./release-artifacts

      - name: Create staging release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          cd ./release-artifacts
          if [ -f build.zip ]; then
            echo "Found build.zip, creating release with TAG=$TAG and NOTE=$NOTE"
            gh release create "$TAG" ./build.zip --notes "$NOTE" || { echo "Release creation failed: $?"; exit 0; }
          else
            echo "No build.zip found, skipping release"
            ls -la
            exit 0
          fi

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./release-artifacts

      - name: Create production release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          cd ./release-artifacts
          if [ -f build.zip ]; then
            echo "Found build.zip, creating release with TAG=$TAG and NOTE=$NOTE"
            gh release create "$TAG" ./build.zip --notes "$NOTE" || { echo "Release creation failed: $?"; exit 0; }
          else
            echo "No build.zip found, skipping release"
            ls -la
            exit 0
          fi
