name: CI Dev Deployment (CI 開發部署)
on:
  push:
    branches: [ master ]  # 使用 master 分支

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev (開發環境)
    steps:
      - name: Checkout code (簽出代碼)
        uses: actions/checkout@v4

      - name: Prepare deployment (準備部署)
        run: echo "Preparing deployment to dev environment"

  build:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (簽出代碼)
        uses: actions/checkout@v4

      - name: Simulate build (模擬構建)
        run: |
          echo "Generating build artifact"
          zip -r build.zip . -x "*.git*"  # 壓縮整個專案，排除 .git

      - name: Upload artifact (上傳構建成品)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact (構建成品)
          path: build.zip

  deploy-dev-release:
    needs: build
    runs-on: ubuntu-latest
    environment: dev (開發環境)
    steps:
      - name: Download artifact (下載構建成品)
        uses: actions/download-artifact@v4
        with:
          name: build-artifact (構建成品)

      - name: Release Dev Build (發布開發版本)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          gh release create "$TAG" build.zip --notes "$NOTE" --generate-notes  # 創建發布
