name: CI Dev Deployment (CI 開發部署)
on:
  push:
    branches: [ master ]  # 使用 master 分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (結帳代碼)
        uses: actions/checkout@v4
      - name: Simulate build (模擬建置)
        run: |
          echo "Generating build artifact"
          zip -r build.zip . -x "*.git*"
      - name: Upload artifact (上傳構件)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build.zip

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact (下載構件)
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./test-artifacts
      - name: Run Automated Tests (執行自動化測試)
        run: |
          cd ./test-artifacts
          chmod +x ../test-script.sh
          ../test-script.sh || exit 1

  deploy-dev:
    runs-on: ubuntu-latest
    needs: test
    environment: dev
    steps:
      - name: Checkout code (結帳代碼)
        uses: actions/checkout@v4
      - name: Download artifact (下載構件)
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./release-artifacts
      - name: Create dev release (創建 dev 發布)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          cd ./release-artifacts
          if [ -f build.zip ]; then
            echo "Found build.zip, creating release with TAG=$TAG and NOTE=$NOTE"
            gh release create "$TAG" ./build.zip --notes "$NOTE" || { echo "Release creation failed: $?"; exit 0; }
          else
            echo "No build.zip found, skipping release"
            ls -la
            exit 0
          fi

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: staging
    steps:
      - name: Checkout code (結帳代碼)
        uses: actions/checkout@v4
      - name: Download artifact (下載構件)
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./release-artifacts
      - name: Create staging release (創建 staging 發布)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          cd ./release-artifacts
          if [ -f build.zip ]; then
            echo "Found build.zip, creating release with TAG=$TAG and NOTE=$NOTE"
            gh release create "$TAG" ./build.zip --notes "$NOTE" || { echo "Release creation failed: $?"; exit 0; }
          else
            echo "No build.zip found, skipping release"
            ls -la
            exit 0
          fi

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production
    steps:
      - name: Checkout code (結帳代碼)
        uses: actions/checkout@v4
      - name: Download artifact (下載構件)
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./release-artifacts
      - name: Create production release (創建 production 發布)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ vars.BUILD_TAG }}
          NOTE: ${{ vars.RELEASE_NOTE }}
        run: |
          cd ./release-artifacts
          if [ -f build.zip ]; then
            echo "Found build.zip, creating release with TAG=$TAG and NOTE=$NOTE"
            gh release create "$TAG" ./build.zip --notes "$NOTE" || { echo "Release creation failed: $?"; exit 0; }
          else
            echo "No build.zip found, skipping release"
            ls -la
            exit 0
          fi
